name: Metrics

on:
  schedule: [{ cron: "0 15 * * *" }] 
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: "activity"
          config_timezone: "Asia/Seoul"
